### ISSUE TITLE
Fix rtl button icon

### ISSUE THREAD

**Issue by robb-j** [digitalinteraction/deconf-ui-toolkit#50]
From PlanetRed

```css
/* TODO: move to deconf */
.button .icon:first-child:not(:last-child) {
  margin-left: unset;
  margin-right: unset;
  margin-inline-start: calc(-0.75em - 1px);
  margin-inline-end: 0.375em;
}
```
