### ISSUE TITLE
Add overflow hack to `WhatsOnView`

### ISSUE THREAD

**Issue by robb-j** [digitalinteraction/deconf-ui-toolkit#63]
The css columns break on firefox and adding this fixes it for some reason.

```css
.whatsOnView .sessionTile {
  // This fixes firefox breaking up tiles across multiple columns for some reason
  overflow: hidden;
}
```
