### ISSUE TITLE
Improve use of `line-height` in Schedule / WhatsOn views

### ISSUE THREAD

**Issue by robb-j** [digitalinteraction/deconf-ui-toolkit#74]
The `line-height` property is not well thought out and leads to lots of whitespace and makes the design more bloated.

```css
p.sessionTile-description {
    line-height: 1.3
}
h2.sessionTile-title {
    line-height: 1;
    margin-bottom: 0.5rem;
}
.speakerGrid-headshot {
    line-height: 1;
}
```

Could tighten up the UI
